<?php $title = $this->translate('Sign Up') ?>

<?php $this->headTitle($title) ?>

<div class="page-inner">
    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-3 center">
                <div class="login-box">
                    <a href="index.html" class="logo-name text-lg text-center">Mpay</a>
                    <p class="text-center m-t-md">Create a Mpay's account</p>
                    <form class="m-t-md" action="" method="post">
                        <?php if ($this->error): ?>
                            <div class="col_full">
                                <div class="alert alert-danger">
                                    <strong>Error!</strong> <?php echo $this->error ?>
                                </div>
                            </div>
                        <?php endif; ?>

                        <?php $element  = $this->form->get('username') ?>
                        <?php $messages = $element->getMessages() ?>
                        <div class="form-group <?php if (count($messages)) echo 'has-error' ?>">
                            <div class="col_full">
                                <?php echo $this->formText($element) ?>
                                <?php if (count($messages)): ?>
                                    <span class="help-block"><?php echo implode(', ', $messages) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php unset($element, $messages) ?>

                        <?php $element  = $this->form->get('password') ?>
                        <?php $messages = $element->getMessages() ?>
                        <div class="form-group <?php if (count($messages)) echo 'has-error' ?>">
                            <div class="col_full">
                                <?php echo $this->formPassword($element) ?>
                                <?php if (count($messages)): ?>
                                    <span class="help-block"><?php echo implode(', ', $messages) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php unset($element, $messages) ?>

                        <?php $element  = $this->form->get('confirm_password') ?>
                        <?php $messages = $element->getMessages() ?>
                        <div class="form-group <?php if (count($messages)) echo 'has-error' ?>">
                            <div class="col_full">
                                <?php echo $this->formPassword($element) ?>
                                <?php if (count($messages)): ?>
                                    <span class="help-block"><?php echo implode(', ', $messages) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php unset($element, $messages) ?>

                        <?php $element  = $this->form->get('email') ?>
                        <?php $messages = $element->getMessages() ?>
                        <div class="form-group <?php if (count($messages)) echo 'has-error' ?>">
                            <div class="col_full">
                                <?php echo $this->formEmail($element) ?>
                                <?php if (count($messages)): ?>
                                    <span class="help-block"><?php echo implode(', ', $messages) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php unset($element, $messages) ?>

                        <?php $element  = $this->form->get('first_name') ?>
                        <?php $messages = $element->getMessages() ?>
                        <div class="form-group <?php if (count($messages)) echo 'has-error' ?>">
                            <div class="col_full">
                                <?php echo $this->formText($element) ?>
                                <?php if (count($messages)): ?>
                                    <span class="help-block"><?php echo implode(', ', $messages) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php unset($element, $messages) ?>

                        <?php $element  = $this->form->get('last_name') ?>
                        <?php $messages = $element->getMessages() ?>
                        <div class="form-group <?php if (count($messages)) echo 'has-error' ?>">
                            <div class="col_full">
                                <?php echo $this->formText($element) ?>
                                <?php if (count($messages)): ?>
                                    <span class="help-block"><?php echo implode(', ', $messages) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php unset($element, $messages) ?>

                        <button type="submit" class="btn btn-success btn-block m-t-xs">Register</button>
                        <p class="text-center m-t-xs text-sm">Already have an account?</p>
                        <a href="<?php echo $this->url('login') ?>" class="btn btn-default btn-block m-t-xs">Login</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
