<?php if (count($this->breadcrumbs)): ?>
    <ol class="breadcrumb container">
        <li><a href="<?php echo $this->url('cpanel') ?>"><?php echo $this->translate('Home') ?></a></li>
        <?php $counter = 0 ?>
        <?php foreach ($this->breadcrumbs as $url => $label): ?>
            <li<?php if ($counter === (count($breadcrumbs) - 1)) echo ' class="active"' ?>>
                <?php if ($url): ?>
                    <a href="<?php echo $url ?>">
                    <?php endif; ?>
                    <?php echo $label ?>
                    <?php if ($url): ?>
                    </a>
                <?php endif; ?>
                <?php $counter ++ ?>
            </li>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>

