<?php if (count($this->pages)): ?>
    <ol class="container breadcrumb">
        <li>
            <a href="<?php echo $this->url('cpanel') ?>"><?php echo $this->translate('Cpanel') ?></a>
        </li>
        <?php $counter = 0 ?>
        <?php foreach ($this->pages as $index => $page): ?>
            <?php if ($page->getLabel() == 'Cpanel' || strtolower($page->getLabel()) == 'hidden') continue; ?>
            <li<?php if ($counter === (count($this->pages) - 1)) echo ' class="active"' ?>>
                <a href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a>
            </li>
            <?php $counter ++ ?>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>
