<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Title -->
        <?php echo $this->headTitle() ?>
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta charset="UTF-8">
        <meta name="description" content="Admin Dashboard Template" />
        <meta name="keywords" content="admin,dashboard" />
        <meta name="author" content="Steelcoders" />

        <!-- Styles -->

        <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/pace-master/themes/blue/pace-theme-flash.css') ?>" rel="stylesheet"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/uniform/css/uniform.default.min.css') ?>" rel="stylesheet"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/fontawesome/css/font-awesome.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/line-icons/simple-line-icons.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/waves/waves.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/switchery/switchery.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/3d-bold-navigation/css/style.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/slidepushmenus/css/component.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/weather-icons-master/css/weather-icons.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/metrojs/MetroJs.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/toastr/toastr.min.css') ?>" rel="stylesheet" type="text/css"/>

        <!-- Theme Styles -->
        <link href="<?php echo $this->basePath('cpanel-assets/assets/css/modern.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/css/custom.css') ?>" class="theme-color" rel="stylesheet" type="text/css"/>

    </head>
    <body class="page-header-fixed compact-menu page-horizontal-bar">
        <div class="overlay"></div>
        <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right" id="cbp-spmenu-s1">
            <h3><span class="pull-left">Chat</span><a href="javascript:void(0);" class="pull-right" id="closeRight"><i class="fa fa-times"></i></a></h3>
            <div class="slimscroll">
                <a href="javascript:void(0);" class="showRight2"><img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar2.png') ?>" alt=""><span>Sandra smith<small>Hi! How're you?</small></span></a>
                <a href="javascript:void(0);" class="showRight2"><img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar3.png') ?>" alt=""><span>Amily Lee<small>Hi! How're you?</small></span></a>
                <a href="javascript:void(0);" class="showRight2"><img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar4.png') ?>" alt=""><span>Christopher Palmer<small>Hi! How're you?</small></span></a>
                <a href="javascript:void(0);" class="showRight2"><img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar5.png') ?>" alt=""><span>Nick Doe<small>Hi! How're you?</small></span></a>
                <a href="javascript:void(0);" class="showRight2"><img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar2.png') ?>" alt=""><span>Sandra smith<small>Hi! How're you?</small></span></a>
                <a href="javascript:void(0);" class="showRight2"><img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar3.png') ?>" alt=""><span>Amily Lee<small>Hi! How're you?</small></span></a>
                <a href="javascript:void(0);" class="showRight2"><img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar4.png') ?>" alt=""><span>Christopher Palmer<small>Hi! How're you?</small></span></a>
                <a href="javascript:void(0);" class="showRight2"><img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar5.png') ?>" alt=""><span>Nick Doe<small>Hi! How're you?</small></span></a>
            </div>
        </nav>
        <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right" id="cbp-spmenu-s2">
            <h3><span class="pull-left">Sandra Smith</span> <a href="javascript:void(0);" class="pull-right" id="closeRight2"><i class="fa fa-angle-right"></i></a></h3>
            <div class="slimscroll chat">
                <div class="chat-item chat-item-left">
                    <div class="chat-image">
                        <img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar2.png') ?>" alt="">
                    </div>
                    <div class="chat-message">
                        Hi There!
                    </div>
                </div>
                <div class="chat-item chat-item-right">
                    <div class="chat-message">
                        Hi! How are you?
                    </div>
                </div>
                <div class="chat-item chat-item-left">
                    <div class="chat-image">
                        <img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar2.png') ?>" alt="">
                    </div>
                    <div class="chat-message">
                        Fine! do you like my project?
                    </div>
                </div>
                <div class="chat-item chat-item-right">
                    <div class="chat-message">
                        Yes, It's clean and creative, good job!
                    </div>
                </div>
                <div class="chat-item chat-item-left">
                    <div class="chat-image">
                        <img src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar2.png') ?>" alt="">
                    </div>
                    <div class="chat-message">
                        Thanks, I tried!
                    </div>
                </div>
                <div class="chat-item chat-item-right">
                    <div class="chat-message">
                        Good luck with your sales!
                    </div>
                </div>
            </div>
            <div class="chat-write">
                <form class="form-horizontal" action="javascript:void(0);">
                    <input type="text" class="form-control" placeholder="Say something">
                </form>
            </div>
        </nav>
        <form class="search-form" action="#" method="GET">
            <div class="input-group">
                <input type="text" name="search" class="form-control search-input" placeholder="Search...">
                <span class="input-group-btn">
                    <button class="btn btn-default close-search waves-effect waves-button waves-classic" type="button"><i class="fa fa-times"></i></button>
                </span>
            </div><!-- Input Group -->
        </form><!-- Search Form -->
        <main class="page-content content-wrap">
            <div class="navbar">
                <div class="navbar-inner container">
                    <div class="sidebar-pusher">
                        <a href="javascript:void(0);" class="waves-effect waves-button waves-classic push-sidebar">
                            <i class="fa fa-bars"></i>
                        </a>
                    </div>
                    <div class="logo-box">
                        <a href="/" class="logo-text"><span>Mpay</span></a>
                    </div><!-- Logo Box -->
                    <div class="search-button">
                        <a href="javascript:void(0);" class="waves-effect waves-button waves-classic show-search"><i class="fa fa-search"></i></a>
                    </div>
                    <div class="topmenu-outer">
                        <div class="top-menu">
                            <ul class="nav navbar-nav navbar-left">
                                <li>
                                    <a href="javascript:void(0);" class="waves-effect waves-button waves-classic sidebar-toggle"><i class="fa fa-bars"></i></a>
                                </li>
                                <li>
                                    <?php /*<a href="#cd-nav" class="waves-effect waves-button waves-classic cd-nav-trigger"><i class="fa fa-diamond"></i></a>*/?>
                                </li>
                                <li>
                                    <a href="javascript:void(0);" class="waves-effect waves-button waves-classic toggle-fullscreen"><i class="fa fa-expand"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown">
                                        <i class="fa fa-cogs"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-md dropdown-list theme-settings" role="menu">
                                        <li class="li-group">
                                            <ul class="list-unstyled">
                                                <li class="no-link" role="presentation">
                                                    Fixed Header
                                                    <div class="ios-switch pull-right switch-md">
                                                        <input type="checkbox" class="js-switch pull-right fixed-header-check" checked>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="li-group">
                                            <ul class="list-unstyled">
                                                <li class="no-link" role="presentation">
                                                    Fixed Sidebar
                                                    <div class="ios-switch pull-right switch-md">
                                                        <input type="checkbox" class="js-switch pull-right fixed-sidebar-check">
                                                    </div>
                                                </li>
                                                <li class="no-link" role="presentation">
                                                    Toggle Sidebar
                                                    <div class="ios-switch pull-right switch-md">
                                                        <input type="checkbox" class="js-switch pull-right toggle-sidebar-check">
                                                    </div>
                                                </li>
                                                <li class="no-link" role="presentation">
                                                    Compact Menu
                                                    <div class="ios-switch pull-right switch-md">
                                                        <input type="checkbox" class="js-switch pull-right compact-menu-check">
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="no-link"><button class="btn btn-default reset-options">Reset Options</button></li>
                                    </ul>
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="javascript:void(0);" class="waves-effect waves-button waves-classic show-search"><i class="fa fa-search"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown"><i class="fa fa-envelope"></i><span class="badge badge-success pull-right">4</span></a>
                                    <ul class="dropdown-menu title-caret dropdown-lg" role="menu">
                                        <li><p class="drop-title">You have 4 new  messages !</p></li>
                                        <li class="dropdown-menu-list slimscroll messages">
                                            <ul class="list-unstyled">
                                                <li>
                                                    <a href="#">
                                                        <div class="msg-img"><div class="online on"></div><img class="img-circle" src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar2.png') ?>" alt=""></div>
                                                        <p class="msg-name">Sandra Smith</p>
                                                        <p class="msg-text">Hey ! I'm working on your project</p>
                                                        <p class="msg-time">3 minutes ago</p>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <div class="msg-img"><div class="online off"></div><img class="img-circle" src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar4.png') ?>" alt=""></div>
                                                        <p class="msg-name">Amily Lee</p>
                                                        <p class="msg-text">Hi David !</p>
                                                        <p class="msg-time">8 minutes ago</p>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <div class="msg-img"><div class="online off"></div><img class="img-circle" src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar3.png') ?>" alt=""></div>
                                                        <p class="msg-name">Christopher Palmer</p>
                                                        <p class="msg-text">See you soon !</p>
                                                        <p class="msg-time">56 minutes ago</p>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <div class="msg-img"><div class="online on"></div><img class="img-circle" src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar5.png') ?>" alt=""></div>
                                                        <p class="msg-name">Nick Doe</p>
                                                        <p class="msg-text">Nice to meet you</p>
                                                        <p class="msg-time">2 hours ago</p>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <div class="msg-img"><div class="online on"></div><img class="img-circle" src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar2.png') ?>" alt=""></div>
                                                        <p class="msg-name">Sandra Smith</p>
                                                        <p class="msg-text">Hey ! I'm working on your project</p>
                                                        <p class="msg-time">5 hours ago</p>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <div class="msg-img"><div class="online off"></div><img class="img-circle" src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar4.png') ?>" alt=""></div>
                                                        <p class="msg-name">Amily Lee</p>
                                                        <p class="msg-text">Hi David !</p>
                                                        <p class="msg-time">9 hours ago</p>
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="drop-all"><a href="#" class="text-center">All Messages</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown"><i class="fa fa-bell"></i><span class="badge badge-success pull-right">3</span></a>
                                    <ul class="dropdown-menu title-caret dropdown-lg" role="menu">
                                        <li><p class="drop-title">You have 3 pending tasks !</p></li>
                                        <li class="dropdown-menu-list slimscroll tasks">
                                            <ul class="list-unstyled">
                                                <li>
                                                    <a href="#">
                                                        <div class="task-icon badge badge-success"><i class="icon-user"></i></div>
                                                        <span class="badge badge-roundless badge-default pull-right">1min ago</span>
                                                        <p class="task-details">New user registered.</p>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <div class="task-icon badge badge-danger"><i class="icon-energy"></i></div>
                                                        <span class="badge badge-roundless badge-default pull-right">24min ago</span>
                                                        <p class="task-details">Database error.</p>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <div class="task-icon badge badge-info"><i class="icon-heart"></i></div>
                                                        <span class="badge badge-roundless badge-default pull-right">1h ago</span>
                                                        <p class="task-details">Reached 24k likes</p>
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="drop-all"><a href="#" class="text-center">All Tasks</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown">
                                        <span class="user-name">
                                            <?php $manager = $this->mpayManager() ?>
                                            <?php $user    = $manager->getLoggedInUser() ?>
                                            <?php if ($user): ?>
                                                <?php if ($user->getFirstName() || $user->getLastName()): ?>
                                                        <?php echo $user->getFirstName() ?>&nbsp;<?php echo $user->getLastName() ?>
                                                    <?php else: ?>
                                                        <?php echo $user->getUsername() ?>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            <i class="fa fa-angle-down"></i>
                                        </span>
                                        <img class="img-circle avatar" src="<?php echo $this->basePath('cpanel-assets/assets/images/avatar1.png') ?>" width="40" height="40" alt="">
                                    </a>
                                    <ul class="dropdown-menu dropdown-list" role="menu">
                                        <li role="presentation"><a href="profile.html"><i class="fa fa-user"></i>Profile</a></li>
                                        <li role="presentation"><a href="calendar.html"><i class="fa fa-calendar"></i>Calendar</a></li>
                                        <li role="presentation"><a href="inbox.html"><i class="fa fa-envelope"></i>Inbox<span class="badge badge-success pull-right">4</span></a></li>
                                        <li role="presentation" class="divider"></li>
                                        <li role="presentation"><a href="lock-screen.html"><i class="fa fa-lock"></i>Lock screen</a></li>
                                        <li role="presentation"><a href="login.html"><i class="fa fa-sign-out m-r-xs"></i>Log out</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('logout') ?>" class="log-out waves-effect waves-button waves-classic">
                                        <span><i class="fa fa-sign-out m-r-xs"></i>Log out</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);" class="waves-effect waves-button waves-classic" id="showRight">
                                        <i class="fa fa-comments"></i>
                                    </a>
                                </li>
                            </ul><!-- Nav -->
                        </div><!-- Top Menu -->
                    </div>
                </div>
            </div><!-- Navbar -->
            <div class="page-sidebar sidebar horizontal-bar">
                <div class="page-sidebar-inner">
                    <?php echo $this->partial('cpanel/main-navigation.phtml', array('navigation' => $this->navigation('cpanel-nav'))) ?>
                </div><!-- Page Sidebar Inner -->
            </div><!-- Page Sidebar -->
            <div class="page-inner">
                <div class="page-breadcrumb">
                    <?php echo $this->navigation('cpanel-nav')
                              ->breadcrumbs()
                              ->setMinDepth(0)
                              ->setPartial('cpanel/breadcrumbs.phtml') ?>
                </div>
                <div class="page-title">
                    <div class="container">
                        <h3>
                            <?php $titleChinks = $this->headTitle() ?>
                            <?php $title       = (isset($titleChinks[0]) && $titleChinks[0]) ? $titleChinks[0] : 'Cpanel' ?>
                            <?php echo $title ?>
                        </h3>
                    </div>
                </div>
                <div id="main-wrapper" class="container">
                    <?php echo $this->content; ?>
                </div><!-- Main Wrapper -->
                <div class="page-footer">
                    <div class="container">
                        <p class="no-s">2015 &copy; Modern by Steelcoders.</p>
                    </div>
                </div>
            </div><!-- Page Inner -->
        </main><!-- Page Content -->

        <?php /* <!-- Fa fa-diamond -->
        <nav class="cd-nav-container" id="cd-nav">
            <header>
                <h3>Navigation</h3>
                <a href="#0" class="cd-close-nav">Close</a>
            </header>
            <ul class="cd-nav list-unstyled">
                <li class="cd-selected" data-menu="index">
                    <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-home"></i>
                        </span>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li data-menu="profile">
                    <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-user"></i>
                        </span>
                        <p>Profile</p>
                    </a>
                </li>
                <li data-menu="inbox">
                    <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-envelope"></i>
                        </span>
                        <p>Mailbox</p>
                    </a>
                </li>
                <li data-menu="#">
                    <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-tasks"></i>
                        </span>
                        <p>Tasks</p>
                    </a>
                </li>
                <li data-menu="#">
                    <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-cog"></i>
                        </span>
                        <p>Settings</p>
                    </a>
                </li>
                <li data-menu="calendar">
                    <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-calendar"></i>
                        </span>
                        <p>Calendar</p>
                    </a>
                </li>
            </ul>
        </nav>
        */?>
        <div class="cd-overlay"></div>

        <!-- Javascripts -->

        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/js/pages/dashboard.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/js/modern.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/metrojs/MetroJs.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/curvedlines/curvedLines.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/flot/jquery.flot.tooltip.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/flot/jquery.flot.resize.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/flot/jquery.flot.symbol.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/flot/jquery.flot.time.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/flot/jquery.flot.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/toastr/toastr.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-counterup/jquery.counterup.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/waypoints/jquery.waypoints.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/3d-bold-navigation/js/main.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/waves/waves.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/classie/classie.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/uniform/jquery.uniform.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/switchery/switchery.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/bootstrap/js/bootstrap.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-blockui/jquery.blockui.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/pace-master/pace.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-ui/jquery-ui.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery/jquery-2.1.4.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/3d-bold-navigation/js/modernizr.js')) ?>
        <?php echo $this->headScript() ?>
    </body>
</html>
