<?php $this->headTitle('Access Denied') ?>

<section id="content">
    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div id="js-alerts" class="panel panel-white">
                    <div class="panel-body">
                        <div role="alert" class="alert alert-warning alert-dismissible fade in">
                            <h4>Access Denied</h4>
                            <p>You have insufficient privileges to access this page.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

