<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php echo $this->headTitle() ?>
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta charset="UTF-8">
        <meta name="description" content="Admin Dashboard Template" />
        <meta name="keywords" content="admin,dashboard" />
        <meta name="author" content="Steelcoders" />
        <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/pace-master/themes/blue/pace-theme-flash.css') ?>" rel="stylesheet"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/uniform/css/uniform.default.min.css') ?>" rel="stylesheet"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/fontawesome/css/font-awesome.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/line-icons/simple-line-icons.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/waves/waves.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/switchery/switchery.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/3d-bold-navigation/css/style.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/css/modern.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/css/custom.css') ?>" class="theme-color" rel="stylesheet" type="text/css"/>
        <script src="<?php echo $this->basePath('cpanel-assets/assets/plugins/3d-bold-navigation/js/modernizr.js') ?>"></script>
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="page-login">
        <div class="page-content">
            <main class="page-content">
                <?php echo $this->content; ?>
            </main>
        </div>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/js/modern.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/waves/waves.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/classie/classie.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/uniform/jquery.uniform.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/switchery/switchery.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/bootstrap/js/bootstrap.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-blockui/jquery.blockui.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/pace-master/pace.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-ui/jquery-ui.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery/jquery-2.1.4.min.js')) ?>
        <?php echo $this->headScript() ?>
    </body>
</html>
