<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <!-- Title -->
        <title>Modern | Login - Sign in</title>
        
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta charset="UTF-8">
        <meta name="description" content="Admin Dashboard Template" />
        <meta name="keywords" content="admin,dashboard" />
        <meta name="author" content="Steelcoders" />
        
        <!-- Styles -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/pace-master/themes/blue/pace-theme-flash.css') ?>" rel="stylesheet"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/uniform/css/uniform.default.min.css') ?>" rel="stylesheet"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/fontawesome/css/font-awesome.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/line-icons/simple-line-icons.css') ?>" rel="stylesheet" type="text/css"/>	
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/offcanvasmenueffects/css/menu_cornerbox.css') ?>" rel="stylesheet" type="text/css"/>	
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/waves/waves.min.css') ?>" rel="stylesheet" type="text/css"/>	
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/switchery/switchery.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/plugins/3d-bold-navigation/css/style.css') ?>" rel="stylesheet" type="text/css"/>	
        
        <!-- Theme Styles -->
        <link href="<?php echo $this->basePath('cpanel-assets/assets/css/modern.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/css/themes/green.css') ?>" class="theme-color" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->basePath('cpanel-assets/assets/css/custom.css" rel="stylesheet') ?>" type="text/css"/>
        
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/3d-bold-navigation/js/modernizr.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/offcanvasmenueffects/js/snap.svg-min.js')) ?>
        
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <section class="main-content">
            <div class="container">
                <?php echo $this->content ?>
            </div>
        </section>
    </body>
    
    <!-- Javascripts -->
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery/jquery-2.1.4.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-ui/jquery-ui.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/pace-master/pace.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-blockui/jquery.blockui.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/bootstrap/js/bootstrap.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/switchery/switchery.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/uniform/jquery.uniform.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/offcanvasmenueffects/js/classie.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/plugins/waves/waves.min.js')) ?>
        <?php $this->headScript()->prependFile($this->basePath('cpanel-assets/assets/js/modern.min.js')) ?>
</html>
