<?php $this->headTitle('Users') ?>

<section id="content">
    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Username</th>
                            <th>Role</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->users as $user): ?>
                            <tr>
                                <td><?php echo $user->getFirstName() ?></td>
                                <td><?php echo $user->getLastName() ?></td>
                                <td><?php echo $user->getEmail() ?></td>
                                <td><?php echo $user->getRole() ?></td>
                                <td><?php echo $user->getStatus() ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
